### ISSUE TITLE
Random Hentai crashes frequently!

### ISSUE THREAD

**Issue by Foxybutt3214** [SonicMastr/Random-Hentai#1]
This app is great, but it tends to crash after viewing a small amount of images. The error code is as follows,

`An error occurred:`
`[string "?"]:25: Error loading image.`

Attempting to press X to restart as it prompts me to causes another error,

`An error occurred:`
`[string "?"]:1: Network is already inited`

The only way to fix this problem is to exit out to the livearea and to actually restart the application manually. Eventually the error will rear its ugly head again though.

**Comment by SonicMastr** [comment]
The Line 1 error is simple and I should be able to fix soon so that you can at least restart properly. 

I'm looking into the images not loading. If you are able to, can you upload the post.json file located in `ux0:data/post.json` once the application crashes again?

**Comment by ghost** [comment]
I had a crash too because the image width is not 8 pixel aligned (the default gxm linear texture stride) . The same image will crash vitashell as well. At some point there was an erroneous assumption that the texture width will be the same as the image width.

**Comment by SonicMastr** [comment]
@Foxybutt3214 The issue has been fixed with the latest commit. I've also added an updated release with this fix.

@cuevavirus Thank you for giving me some pointers to this issue. Thanks to you I was able to fix the vita2d library and also rebuild lpp-vita with the fix to update the eboot. The issue has been fixed in the latest release :)
